// 反馈列表展示用的几个小转换——GitHub Issue 正文本身是 markdown，这个项目
// 没有引入 markdown 渲染库，只需要处理反馈系统自己生成的这两种固定格式：
// 提交时带的图片 markdown，和评论里带的作者名前缀/自动评估签名。

const IMAGE_MD_RE = /!\[[^\]]*\]\((https?:\/\/\S+?)\)/g;

// 把正文里的图片 markdown 摘出来单独渲染成真的 <img>，剩下的纯文字部分
// 保留换行（调用方用 white-space:pre-wrap 展示）。
export function extractImages(body) {
  const images = [];
  const text = (body || '').replace(IMAGE_MD_RE, (_, url) => { images.push(url); return ''; }).trim();
  return { text, images };
}

const AUTHOR_PREFIX_RE = /^\*\*(.+?)\*\*[：:]\s*/;
const BOT_SIGNATURE_RE = /\n*---\n*_Generated by \[Claude Code\][^\n]*_\s*$/;

// 评论只读展示（app 里不支持加评论）——要么是自动评估留的（末尾带
// "_Generated by [Claude Code]..._" 签名），要么是别的什么人直接在
// GitHub 网页上手动回的（实际上目前几乎都是维护者跟真人讨论后写的决策
// 总结，不是真的匿名访客留言，所以标签用"产品反馈"而不是"匿名"——用户
// 反馈 2026-08-12："不要叫匿名了"）。两种都识别不出时归到这个默认标签，
// 不是新发明的第三种格式。
export function parseComment(body) {
  const raw = body || '';
  if (/_Generated by \[Claude Code\]/.test(raw)) {
    return { author: '自动评估', isAuto: true, text: raw.replace(BOT_SIGNATURE_RE, '').trim() };
  }
  const m = raw.match(AUTHOR_PREFIX_RE);
  if (m) return { author: m[1], isAuto: false, text: raw.slice(m[0].length).trim() };
  return { author: '产品反馈', isAuto: false, text: raw.trim() };
}

const SUBMITTER_PREFIX_RE = /^\*\*提交人：(.+?)\*\*\n\n/;

// 提交反馈时正文最前面拼的 "**提交人：X**" 前缀（server/feedbackReporter.js
// createFeedbackIssue）——跟评论的作者前缀格式故意不同（"提交人：" vs 纯
// 名字+冒号），避免两种解析互相误判。
export function extractAuthor(body) {
  const raw = body || '';
  const m = raw.match(SUBMITTER_PREFIX_RE);
  if (m) return { author: m[1], rest: raw.slice(m[0].length) };
  return { author: null, rest: raw };
}

// 状态文案直接从 issue 现有的 state/labels 推出来，不新建一套状态机——
// 跟自动评估打的标签（accepted/design）保持同一套语义来源。
export function statusOf(issue) {
  if (issue.state === 'closed') return { text: '已处理', tone: 'done' };
  if (issue.labels?.includes('accepted') || issue.labels?.includes('design')) return { text: '评估中', tone: 'progress' };
  return { text: '待处理', tone: 'new' };
}

export function formatTime(iso) {
  if (!iso) return '';
  return new Date(iso).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' });
}
